# Simulation
In this lesson, we will work through several examples of using random numbers to simulate real-world scenarios.

In [141]:
#importing libraries:-

#For numerical computing and array operations.
import numpy as np
#For data manipulation and analysis.
import pandas as pd
# curriculum example visualizations
import viz 
#For creating visualizations and plots.
import matplotlib.pyplot as plt

In [142]:
#preset the number of simulations to 100,000 for all the questions in this exercise
n_simulations =100_000

#More Simulations gives higher Accuracy

#### 1 How likely is it that you roll doubles when rolling two dice?



In [89]:
 # (1,1) (2,2) (3,3) (4,4) (5,5) (6,6) are the double if we have two dice
# There are 6 chances for a double out of 36 rolls
6/36 

0.16666666666666666

In [ ]:
#or

In [123]:
#######Now use simulation##########

#number of dice
n_dice = 2 

#possible outcomes
outcomes = [1,2,3,4,5,6]

#use random choice to get the simulation from the above list
rolls = np.random.choice(outcomes, size=(n_simulations, n_dice))

#compares the values in the first column with the values in the second column element-wise
prob_doubles = (rolls[:,0] == rolls[:,1]).mean()
print(f'Probability of rolling doubles when rolling two dice across 100k simulations :',prob_doubles)

Probability of rolling doubles when rolling two dice across 100k simulations : 0.16505


### 2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [138]:
####### use simulation#######

#number of coins
n_coins = 8

#possible outcomes
outcomes = ['H','T']

#use random choice to get the simulation from the above list
coinflips = np.random.choice(outcomes, size=(n_simulations, n_coins))

#'coinflips' array now have each row representing a simulation and each column representing a coin

#Boolean mask that checks if each element in the coinflips array is equal to 'H' and
#counts the occurrences of 'H' in each row (simulation) of the coinflips array.
flips_by_sim = (coinflips == 'H').sum(axis=1)

#Landing on Heads exactly 3 times
land_3heads =(flips_by_sim == 3).mean()
print(f'Probability of getting  exactly 3 heads, when 8 coins are flipped:',land_3heads)

#Landing on Heads more than 3 times
land_more_3heads = (flips_by_sim > 3).mean()
print(f'Probability of getting  more than 3 heads, when 8 coins are flipped:',land_more_3heads)


Probability of getting  exactly 3 heads, when 8 coins are flipped: 0.21793
Probability of getting  more than 3 heads, when 8 coins are flipped: 0.63624


#### 3.  There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [144]:
# 3 web development class  per 1 data science class = 1/4 i.e  25% of alumni are data science 
# 2 billboards odds of both having a data science student on it
# 25% chance per billboard * 2 billboards = 1/8

(1/4) *(1/4)

0.0625

In [ ]:
#or

In [159]:
####### Now use simulation#######

#number of billboards
n_billboards = 2

#possible outcomes with 4 classes
#outcomes = ['wd', 'wd', 'wd', 'ds']
outcomes = ['wd','ds']

#use random choice to get the simulation from the above list
#using the probability of 1/4 classes being DS, and 3/4 classes being WD
billboards = np.random.choice(outcomes, size=(n_simulations, n_billboards), p=[0.75, 0.25])

# billboard will be exactly data science
bill_exact_ds = (billboards == 'ds').sum(axis=1).mean()
print(f'Probability that Codeup randomly selects an alumni to put on a billboard, who is a data science alumni :',bill_exact_ds)


#probability that two billboards will be exactly data science
bill_2ds = ((billboards == 'ds').sum(axis=1) == 2).mean()
print(f'Probability that two billboards will be exactly data science alumni :',bill_2ds)


#odds of seeing a billboard that is not 'wd'
odds = bill_2ds/(1-bill_2ds)
print(f'Probability where odds of seeing a billboard that is not "wd" :',odds)





Probability that Codeup randomly selects an alumni to put on a billboard, who is a data science alumni : 0.50064
Probability that two billboards will be exactly data science alumni : 0.0625
Probability where odds of seeing a billboard that is not "wd" : 0.06666666666666667


### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [175]:
mean = 3
sd = 1.5
n_days_inweek = 5

#let's use random normal because we have the mean and standard deviation,sd already given
#poptart purchase data for each day of the week in multiple simulations
poptarts_bought_day = np.random.normal(mean, sd, size=(n_simulations, n_days_inweek ))


#sum of poptarts bought on each day (across columns) per week for each simulation (along rows)
poptarts_bought_per_week = poptarts_bought_day.sum(axis=1)

#probability that poptarts are available on Friday afternoon which means less than 17 poptarts are bought that week
less_than17_pop = (poptarts_bought_per_week <= 16).mean()
print(f'Probability that poptarts are available on Friday afternoon :',less_than17_pop)




Probability that poptarts are available on Friday afternoon : 0.61794


### 5. Compare Heights.Men have an average height of 178 cm and standard deviation of 8cm.Women have a mean of 170, sd = 6cm.Since you have means and standard deviations, you can use np.random.normal to generate observations. If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [181]:
#men's average height in cm
men_avg= 178
#men's standard deviation in cm
men_std=8


#women's average height in cm
women_avg=170
#women's standard deviation in cm
women_std=6



#let's use random normal because we have the mean and standard deviation already given
#find the average heights of men (in cm) 
height_men = np.random.normal(men_avg, men_std, n_simulations)


#checking the height_men array
height_men


array([170.24539976, 193.70205862, 178.49592343, ..., 172.15837392,
       185.90860856, 175.66042328])

In [179]:
##let's use random normal because we have the mean and standard deviation already given
#find the average heights of women (in cm) 
height_women = np.random.normal(women_avg, women_std, n_simulations)


#checking the height_women array
height_women

array([166.68315517, 172.06860384, 169.84542764, ..., 164.13378185,
       168.9353371 , 166.66174784])

In [180]:
#what is the average probability that women are taller then men
wmn_tall_men = (height_women > height_men).mean()
print(f'Probability that women are taller then men:',wmn_tall_men)

Probability that women are taller then men: 0.21114


### 6.When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

### How likely is it that 450 students all download anaconda without an issue?

In [214]:
#possible outcomes, success or failure
outcomes = ['S', 'F']

n_students = 50
#use random choice to get the simulation
#p argument specifies the probability distribution associated with each outcome.
#the p argument is an optional parameter that allows you to specify the probability distribution for each element in the outcomes array or list. 
#It should be a 1-D array-like object (list, tuple, or NumPy array) of the same length as the outcomes array.
downloads = np.random.choice(outcomes, size=(n_simulations, n_students), p = [249/250, 1/250])
#download being success and  no one has an installation issue
(downloads == 'S').sum(axis=1)
# possibility of 50 students download anaconda, no one has an installation issue
x =((downloads == 'S').sum(axis=1) == 50).mean()
print('50 students no issue',x)

n_students = 100
#use random choice to get the simulation
downloads = np.random.choice(outcomes, size=(n_simulations, n_students), p = [249/250, 1/250])
# possibility of 100 students download anaconda, no one has an installation issue
x =((downloads == 'S').sum(axis=1) == 100).mean()
print('100 students no issue',x)


n_students = 150
#use random choice to get the simulation
downloads = np.random.choice(outcomes, size=(n_simulations, n_students), p = [249/250, 1/250])
# possibility of 150 students download anaconda, no one has an installation issue
x =((downloads == 'S').sum(axis=1) == 150).mean()
print('150 students no issue',x)



prob_of_failure = 1/250
n_students = 150
downloads = np.random.random((n_simulations, n_students))
y = ((downloads < prob_of_failure).sum(axis=1) >= 1).mean()
print('Installation issue within the first 150 students that downloaded anaconda:', y)


n_students = 450
#use random choice to get the simulation
downloads = np.random.choice(outcomes, size=(n_simulations, n_students), p = [249/250, 1/250])
# possibility of 450 students download anaconda, no one has an installation issue
x =((downloads == 'S').sum(axis=1) == 450).mean()
print('450 students no issue',x)

50 students no issue 0.815
100 students no issue 0.703
150 students no issue 0.551
Installation issue within the first 150 students that downloaded anaconda: 0.459
450 students no issue 0.164


### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

### How likely is it that a food truck will show up sometime this week?

In [215]:
# Probability of seeing a food truck on any given day
p = 0.7
# Probability of not seeing a food truck on any single day
q = 1 - p

# Number of days (i.e trials)
n_days = 3

#probability of not seeing a food truck in 3 days (all 3 days are "no food truck" outcomes)
probability_not_seeing_truck_in_3_days = q ** n_days

# Probability of seeing a food truck at least once in 3 days
probability_seeing_truck_in_3_days = 1 - probability_not_seeing_truck_in_3_days

print("Probability of not seeing a food truck in 3 days:", probability_not_seeing_truck_in_3_days)
print("Probability of seeing a food truck at least once in 3 days:", probability_seeing_truck_in_3_days)


Probability of not seeing a food truck in 3 days: 0.027000000000000014
Probability of seeing a food truck at least once in 3 days: 0.973


In [ ]:
#or

In [ ]:
#####Now using simulations#######

In [216]:
n_days = 3

In [217]:
# 0 = no truck, 1 = truck shows up
trucks = np.random.choice([0, 1], size = (n_simulations, n_days), p = [0.3, 0.7])

#call the variable
trucks

array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 1],
       ...,
       [1, 1, 1],
       [0, 0, 1],
       [1, 0, 1]])

In [220]:
#Probability that no trucks shows up in 3 days
#axis 1 is 0 (or no truck shows up)
no_truck_3days =(trucks.sum(axis = 1) == 0).mean()
print("Probability of not seeing a food truck in 3 days:",no_truck_3days )

Probability of not seeing a food truck in 3 days: 0.026


In [ ]:
How likely is it that a food truck will show up sometime this week

In [222]:
#Probability of seeing a food truck at least once in 3 days
#likelyhood that in axis 1 there is a 1 (or a truck does show up) one or more days
atleast1_truck_3days = (trucks.sum(axis = 1) >= 1).mean()
print("Probability of seeing a food truck at least once in 3 days:",atleast1_truck_3days )

Probability of seeing a food truck at least once in 3 days: 0.974


### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [253]:
# 23 students in class
#number of days in a year
outcomes = range(0, 365) 

#number of students
n_students= 23 

#using random choice to get the possible birthdays
birthdays= np.random.choice(outcomes, size=(n_simulations, n_students))

#call that variable
birthdays

array([[332, 322, 232, ..., 153, 363,  14],
       [191, 232,  21, ..., 206, 343,  55],
       [ 24,  87, 109, ...,  56, 113, 363],
       ...,
       [279, 335, 354, ..., 221, 263, 226],
       [243, 218, 340, ..., 345, 306,  48],
       [142,  90, 314, ...,  51, 102, 334]])

In [244]:
#turn it into a dataframe 
birthdays = pd.DataFrame(birthdays)

#call dataframe
birthdays.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0  216  215  261  183  280  331  165  151  159   76  ...    6    9  194  314   
1  113  196  107  137  295  193   77   62  305  334  ...  244  156   96  207   
2   41  352  192  159   92  113  104  289   89  263  ...  140  230  135   51   
3  173  307  300   37   56  341   17  178  259  305  ...  284  296   85  260   
4  177  164  218  315   98    2  159  231  220   28  ...  146  247  338  264   

    17   18   19   20   21   22  
0   56  119  269  294  269   51  
1  258   32  110  227  252  298  
2  155  141   48  260   45  161  
3   92  228  180  223  272  300  
4  135  238   69  123   88  115  

[5 rows x 23 columns]

In [245]:
# 23 students in class
#If the number of unique birthdays is less than 23 in a simulation, 
#it means that there are at least two people with the same birthday in that particular group(birthday paradox). 

atleast_2sameday_birthday = (birthdays.nunique(axis=1) < 23).mean()
print('probability of having at least two people with the same birthday in a group of 23 people',atleast_2sameday_birthday)

probability of having at least two people with the same birthday in a group of 23 people 0.52


In [256]:
# 20 students in class

#number of days in a year
outcomes = range(0, 365) 

#number of students
n_students= 20 

#let's see what the possibility of birhtdays is with 20 students
birthdays= np.random.choice(outcomes, size=(n_simulations, n_students))

#turn that into a DF
birthdays = pd.DataFrame(birthdays)

#call the DF
birthdays

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0    287   69  177   98   68  183  352  233  182  214   22  100  352  118   
1    155  120  133   39  132  187   40  113  354   14  205   52  347  259   
2     67  207  211  116  127  321   66   97  124  188   81  220  294  248   
3    240  253  261    4  155  318  235  363   14   97  308   79  295  316   
4    182   22  123   81  251  170  146    8   30  105   28  355   53  274   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
995    5  266   35   58  181  303  193  340  275  341   58  150  266  344   
996  103  198   47  167  226  104  104  131  258  341  220  100  240  129   
997   63  114  288  183  312  197  287  199    3  339  278  314  291  109   
998  160  194   47   37   83   55   75   25   28  305  200  362  291   82   
999  266  112  140  270  145  205  150   28  256  236  320  337  232  190   

      14   15   16   17   18   19  
0    204   43    3  175  306  243  
1    183  126   86  168  290   41  
2     71   25  295  298    1  218  
3    353  254  194  298   47  304  
4    255  160  142  237  109  299  
..   ...  ...  ...  ...  ...  ...  
995  101   91   33  310    1   47  
996  206   84  109   25  264  120  
997  216   69  284  277  138  112  
998  193  233  131  184   49  202  
999  160  330   91   46   29  246  

[1000 rows x 20 columns]

In [257]:
#get the probability
prob2_outof23 = (birthdays.nunique(axis=1) < n_students).mean()
print("Probability of two people sharing a birthday out of 20 people in the same room :",prob2_outof23 )

Probability of two people sharing a birthday out of 20 people in the same room : 0.399


In [250]:
# 40 students in class

#number of days in a year
outcomes = range(0, 365) 

#number of students
n_students= 40 

#let's see what the possibility of birhtdays is with 40 students
birthdays = np.random.choice(outcomes, size=(n_simulations, n_students))

#call the DF
birthdays = pd.DataFrame(birthdays)

#get the probability
prob2_outof40 = (birthdays.nunique(axis=1) < n_students).mean()
print("Probability of two people sharing a birthday out of 40 people in the same room :",prob2_outof40 )

Probability of two people sharing a birthday out of 40 people in the same room : 0.908
